version: 2.0

defaults: &defaults
  working_directory: /root/project
  docker:
    - image: compassventures/buildpacks

deploysteps: &deploysteps
  steps:
    - checkout
    - deploy:
        name: Deploy
        command: |
          $CIRCLE_WORKING_DIRECTORY/scripts/deploy_lambda

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
  deploy-dev:
    <<: *defaults
    environment:
      STATE_ENV: development
      AWS_DEFAULT_REGION: us-east-1
    <<: *deploysteps
  deploy-stage:
    <<: *defaults
    environment:
      STATE_ENV: staging
      AWS_DEFAULT_REGION: us-east-1
    <<: *deploysteps
  deploy-prod:
    <<: *defaults
    environment:
      STATE_ENV: production
      AWS_DEFAULT_REGION: us-east-1
    <<: *deploysteps

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
                - develop
  deploy-dev:
    jobs:
      - deploy-dev:
          filters:
            branches:
              only: develop
